XMACRO(align_content,"align-content",stretch,no,no,CSS3,(stretch,center,flex-start,flex-end,space-between,space-around,initial,inherit))
XMACRO(align_items,"align-items",stretch,no,no,CSS3,(stretch,center,flex-start,flex-end,baseline,initial,inherit))
XMACRO(align_self,"align-self",auto,no,no,CSS3,(auto,stretch,center,flex-start,flex-end,baseline,initial,inherit))
XMACRO(all,"all",none,no,no,CSS3,(initial,inherit,unset))
XMACRO(animation,"animation",none 0 ease 0 1 normal none running,no,no,CSS3)
XMACRO(animation_delay,"animation-delay",0s,no,no,CSS3,(TIME,initial,inherit))
XMACRO(animation_direction,"animation-direction",normal,no,no,CSS3,(normal,reverse,alternate,alternate-reverse,initial,inherit))
XMACRO(animation_duration,"animation-duration",0,no,no,CSS3,(TIME,initial,inherit))
XMACRO(animation_fill_mode,"animation-fill-mode",none,no,no,CSS3,(none,forwards,backwards,both,initial,inherit))
XMACRO(animation_iteration_count,"animation-iteration-count",1,no,no,CSS3,(NUMBER,infinite,initial,inherit))
XMACRO(animation_name,"animation-name",none,no,no,CSS3,(KEYFRAMENAME,none,initial,inherit))
XMACRO(animation_play_state,"animation-play-state",running,no,no,CSS3,(paused,running,initial,inherit))
XMACRO(animation_timing_function,"animation-timing-function",ease,no,no,CSS3,(linear,ease,ease-in,ease-out,ease-in-out,step-start,step-end,STEPS,CUBIC_BEZIER,initial,inherit))
XMACRO(backface_visibility,"backface-visibility",visible,no,no,CSS3,(visible,hidden,initial,inherit))
XMACRO(background,"background",scroll,no,yes,CSS1,(initial,inherit))
XMACRO(background_attachment,"background-attachment",scroll,no,no,CSS1,(scroll,fixed,local,initial,inherit))
XMACRO(background_blend_mode,"background-blend-mode",normal,no,no,CSS1,(normal,multiply,screen,overlay,darken,lighten,color-dodge,saturation,color,luminosity))
XMACRO(background_clip,"background-clip",border-box,no,no,CSS3,(border-box,padding-box,content-box,initial,inherit))
XMACRO(background_color,"background-color",transparent,no,yes,CSS1,(color,transparent,initial,inherit))
XMACRO(background_image,"background-image",none,no,no,CSS1,(URL,none,/*fixme*/,initial,inherit))
XMACRO(background_origin,"background-origin",padding-box,no,no,CSS3,(padding-box,border-box,content-box,initial,inherit))
XMACRO(background_position,"background-position",0% 0%,no,yes,CSS1,(left top,left center,left bottom,right top,right center,right bottom,center top,center center,center bottom,/*fixme*/,initial,inherit))
XMACRO(background_repeat,"background-repeat",repeat,no,no,CSS1,(repeat,repeat-x,repeat-y,no-repeat,space,round,initial,inherit))
XMACRO(background_size,"background-size",auto,no,yes,CSS3,(auto,length,percentage,cover,contain,initial,inherit))
XMACRO(border,"border",medium none COLOR,no,yes,CSS1,(initial,inherit))
XMACRO(border_bottom,"border-bottom",medium none COLOR,no,yes,CSS1,(initial,inherit))
XMACRO(border_bottom_color,"border-bottom-color",initial,no,yes,CSS1,(COLOR,transparent,initial,inherit))
XMACRO(border_bottom_left_radius,"border-bottom-left-radius",0,no,yes,CSS3,(LENGTH,PERCENT,initial,inherit))
XMACRO(border_bottom_right_radius0,"border-bottom-right-radius0",no,yes,CSS3,(LENGTH,PERCENT,initial,inherit))
XMACRO(border_bottom_style,"border-bottom-style",none,no,no,CSS1,(none,hidden,dotted,dashed,solid,double,groove,ridge,inset,outset,initial,inherit))
XMACRO(border_bottom_width,"border-bottom-width",medium,no,yes,CSS1,(medium,thin,thick,LENGTH,initial,inherit))
XMACRO(border_collapse,"border-collapse",separate,yes,no,CSS2,(separate,collapse,initial,inherit))
XMACRO(border_color,"border-color",initial,no,yes,CSS1,(COLOR,transparent,initial,inherit))
XMACRO(border_image,"border-image",none 100% 1 0 stretch,no,no,CSS3)
XMACRO(border_image_outset,"border-image-outset",0,no,no,CSS3,(length,number,initial,inherit))
XMACRO(border_image_repeat,"border-image-repeat",stretch,no,no,CSS3,(stretch,repeat,round,space,initial,inherit))
XMACRO(border_image_slice,"border-image-slice",100%,no,no,CSS3,(NUMBER,PERCENT,fill,initial,inherit))
XMACRO(border_image_source,"border-image-source",none,no,no,CSS3,(none,PATH,initial,inherit))
XMACRO(border_image_width,"border-image-width",1,no,no,CSS3,(LENGTH,NUMBER,PERCENT,auto,initial,inherit))
XMACRO(border_left,"border-left",medium none COLOR,no,yes,CSS1,(initial,inherited))
XMACRO(border_left_color,"border-left-color",initial,no,yes,CSS1,(COLOR,transparent,initial,inherit))
XMACRO(border_left_style,"border-left-style",none,no,no,CSS1,(none,hidden,dotted,dashed,solid,double,groove,ridge,inset,outset,initial,inherit))
XMACRO(border_left_width,"border-left-width",medium,no,yes,CSS1,(medium,thin,thick,LENGTH,initial,inherit))
XMACRO(border_radius,"border-radius",0,no,yes,CSS3,(LENGTH,PERCENT,initial,inherit))
XMACRO(border_right,"border-right",medium none COLOR,no,yes,CSS1,(initial,inherit))
XMACRO(border_right_color,"border-right-color",black,no,yes,CSS1,(COLOR,transparent,initial,inherit))
XMACRO(border_right_style,"border-right-style",none,no,no,CSS1,(none,hidden,dotted,dashed,solid,double,groove,ridge,inset,outset,initial,inherit))
XMACRO(border_right_width,"border-right-width",medium,no,yes,CSS1,(medium,thin,thick,LENGTH,initial,inherit))
XMACRO(border_spacing,"border-spacing",2px,yes,yes,CSS2,(/*fixme*/ initial,inherit))
XMACRO(border_style,"border-style",none,no,CSS1,(none,hidden,dotted,dashed,solid,double,groove,ridge,inset,outset,initial,inherit))
XMACRO(border_top,"border-top",medium none COLOR,no,yes,CSS1,(initial,inherit))
XMACRO(border_top_color,"border-top-color",initial,no,yes,CSS1,(COLOR,transparent,initial,inherit))
XMACRO(border_top_left_radius,"border-top-left-radius",0,no,yes,CSS3,(LENGTH,PERCENT,initial,inherit))
XMACRO(border_top_right_radius,"border-top-right-radius",0,no,yes,CSS3,(LENGTH,PERCENT,initial,inherit))
XMACRO(border_top_style,"border-top-style",none,no,no,CSS1,(none,hidden,dotted,dashed,solid,double,groove,ridge,inset,outset,initial,inherit))
XMACRO(border_top_width,"border-top-width",medium,no,yes,CSS1,(medium,thin,thick,LENGTH,initial,inherit))
XMACRO(border_width,"border-width",medium,no,yes,CSS1,(medium,thin,thick,LENGTH,initial,inherit))
XMACRO(bottom,"bottom",auto,no,yes,CSS2,(auto,LENGTH,PERCENT,initial,inherit))
XMACRO(box_decoration_break,"box-decoration-break",slice,no,no,CSS3,(slice,clone,initial,inherit))
XMACRO(box_shadow,"box-shadow",none,no,yes,CSS3,(none/*fixme*/,inset,initial,inherit))
XMACRO(box_sizing,"box-sizing",content-box,no,no,CSS3,(content-box,border-box,initial,inherit))
XMACRO(caption_side,"caption-side",top,yes,no,CSS2,(top,bottom,initial,inherit))
XMACRO(caret_color,"caret-color",auto,yes,no,CSS3,(auto,COLOR))
XMACRO(clear,"clear",none,no,no,CSS1,(none,left,right,both,initial,inherit))
XMACRO(clip,"clip",auto,no,yes,CSS2,(auto/*fixme*/,initial,inherit))
XMACRO(color,"color",initial,yes,yes,CSS1,(COLOR,initial,inherit))
XMACRO(column_count,"column-count",auto,no,yes,CSS3,(NUMBER,auto,initial,inherit))
XMACRO(column_fill,"column-fill",balance,no,no,CSS3,(balance,auto,initial,inherit))
XMACRO(column_gap,"column-gap",normal,no,yes,CSS3,(LENGTH,normal,initial,inherit))
XMACRO(column_rule,"column-rule",medium none COLOR,no,yes,CSS3,(initial inherit))
XMACRO(column_rule_color,"column-rule-color",initial,no,yes,CSS3,(COLOR,initial,inherit))
XMACRO(column_rule_style,"column-rule-style",none,no,no,CSS3,(none,hidden,dotted,dashed,solid,double,groove,ridge,inset,outset,initial,inherit))
XMACRO(column_rule_width,"column-rule-width",medium,no,yes,CSS3,(medium,thin,thick,LENGTH,initial,inherit))
XMACRO(column_span,"column-span",none,no,no,CSS3,(none,all,initial,inherit))
XMACRO(column_width,"column-width",auto,no,yes,CSS3,(auto,LENGTH,initial,inherit))
XMACRO(columns,"columns",auto auto,no,yes,CSS3,(auto,/*fixme*/ initial,inherit))
XMACRO(content,"content",normal,no,no,CSS2,(normal,none,counter,/*fixme*/ open-quote,close-quote,no-open-quote,no-close-quote,initial,inherit))
XMACRO(counter_increment,"counter-increment",none,no,no,CSS3,(none,/*fixme*/ initial,inherit))
XMACRO(counter_reset,"counter-reset",none,no,no,CSS2,(none,/*fixme*/ initial,inherit))
XMACRO(cursor,"cursor",auto,yes,no,CSS2,(alias,all-scroll,auto,cell,context-menu,col-resize,copy,crosshair,default,e-resize,ew-resize,grab,grabbing,help,move,n-resize,ne-resize,nesw-resize,ns-resize,nw-resize,nwse-resize,no-drop,none,not-allowed,pointer,progress,row-resize,s-resize,se-resize,sw-resize,text,URL,vertical-text,w-resize,wait,zoom-in,zoom-out,initial,inherit))
XMACRO(direction,"direction",ltr,yes,no,CSS2,(ltr,rtl,initial,inherit))
XMACRO(display,"display",initial,no,no,CSS1,(inline,block,contents,flex,grid,inline-block,inline-flex,inline-grid,inline-table,list-item,run-in,table,table-caption,table-column-group,table-header-group,table-footer-group,table-row-group,table-cell,table-column,table-row,none,initial,inherit))
XMACRO(empty_cells,"empty-cells",show,yes,no,CSS2,(show,hide,initial,inherit))
XMACRO(filter,"filter",none,no,yes,CSS3,(none,/*fixme*/initial,inherit))
XMACRO(flex,"flex",0 1 auto,no,yes,CSS3,(auto,initial,none,inherit))
XMACRO(flex_basis,"flex-basis",auto,no,yes,CSS3,(NUMBER,auto,initial,inherit))
XMACRO(flex_direction,"flex-direction",row,no,no,CSS3,(row,row-reverse,column,column-reverse,initial,inherit))
XMACRO(flex_flow,"flex-flow",row nowrap,no,no,CSS3,(/*fixme*/initial,inherit))
XMACRO(flex_grow,"flex-grow",0,no,yes,CSS3,(NUMBER,initial,inherit))
XMACRO(flex_shrink,"flex-shrink",1,no,yes,CSS3,(NUMBER,initial,inherit))
XMACRO(flex_wrap,"flex-wrap",nowrap,no,no,CSS3,(nowrap,wrap,wrap-reverse,initial,inherit))
XMACRO(float,"float",none,no,no,CSS1,(none,left,right,initial,inherit))
XMACRO(font,"font",initial,yes,yes,CSS1,(caption,icon,menu,message-box,small-caption,status-bar,initial,inherit))
XMACRO(font_family,"font-family",initial,yes,no,CSS1,(/*fixme*/initial,inherit))
XMACRO(font_kerning,"font-kerning",auto,yes,no,CSS3,(auto,normal,none))
XMACRO(font_size,"font-size",medium,yes,yes,CSS1,(medium,xx-small,x-small,small,large,x-large,xx-large,smaller,larger,LENGTH,PERCENT,initial,inherit))
XMACRO(font_size_adjust,"font-size-adjust",none,yes,yes,CSS3,(NUMBER,none,initial,inherit))
XMACRO(font_stretch,"font-stretch",normal,yes,yes,CSS3,(ultra-condensed,extra-condensed,condensed,semi-condensed,normal,semi-expanded,expanded,extra-expanded,ultra-expanded,initial,inherit))
XMACRO(font_style,"font-style",normal,yes,no,CSS1,(normal,italic,oblique,initial,inherit))
XMACRO(font_variant,"font-variant",normal,yes,no,CSS1,(normal,small-caps,initial,inherit))
XMACRO(font_weight,"font-weight",normal,yes,yes,CSS1,(normal,bold,bolder,lighter,100,200,300,400,500,600,700,800,900,initial,inherit))
XMACRO(grid,"grid",none none none auto auto row,no,yes,CSS1,(none,initial,inherit/*fixme*/))
XMACRO(grid_area,"grid-area",auto/auto/auto/auto,no,yes)
XMACRO(grid_auto_columns,"grid-auto-columns",auto,no,yes,CSS1,(auto,/*fixme*/max-content,min-content,LENGTH,PERCENT))
XMACRO(grid_auto_flow,"grid-auto-flow",row,no,yes,CSS1,(row,column,dense,row dense,column dense))
XMACRO(grid_auto_rows,"grid-auto-rows",auto,no,yes,CSS1,(auto,max-content,min-content,LENGTH))
XMACRO(grid_column,"grid-column",auto/auto,no,yes,CSS1)
XMACRO(grid_column_end,"grid-column-end",auto,no,yes,CSS1,(auto,/*fixme*/))
XMACRO(grid_column_gap,"grid-column-gap",0,no,yes,CSS1,(LENGTH))
XMACRO(grid_column_start,"grid-column-start",auto,no,yes,CSS1,(auto/*fixme*/))
XMACRO(grid_gap,"grid-gap",0 0,no,yes,CSS1)
XMACRO(grid_row,"grid-row",auto/auto,no,yes,CSS1)
XMACRO(grid_row_end,"grid-row-end",auto,no,yes,CSS1)
XMACRO(grid_row_gap,"grid-row-gap",0,no,yes,CSS1,(LENGTH))
XMACRO(grid_row_start,"grid-row-start",auto,no,yes,CSS1)
XMACRO(grid_template,"grid-template",none none none,no,yes,CSS1)
XMACRO(grid_template_areas,"grid-template-areas",none,no,yes,CSS1)
XMACRO(grid_template_columns,"grid-template-columns",none,no,yes,CSS1,(none,auto,max-content,min-content,LENGTH,initial,inherit))
XMACRO(grid_template_rows,"grid-template-rows",none,no,yes,CSS1,(none,auto,max-content,min-content,LENGTH))
XMACRO(hanging_punctuation,"hanging-punctuation",none,yes,no,CSS3,(none,first,last,allow-end,force-end,initial,inherit))
XMACRO(height,"height",auto,no,yes,CSS1,(auto,LENGTH,PERCENT,initial,inherit))
XMACRO(hyphens,"hyphens",manual,yes,no,CSS3,(none,manual,auto,initial,inherit))
XMACRO(isolation,"isolation",auto,no,no,CSS3,(auto,isolate,initial,inherit))
XMACRO(justify_content,"justify-content",flex-start,no,no,CSS3,(flex-start,flex-end,center,space-between,space-around,initial,inherit))
XMACRO(left,"left",auto,no,yes,CSS2,(auto,LENGTH,PERCENT,initial,inherit))
XMACRO(letter_spacing,"letter-spacing",normal,yes,yes,CSS1,(normal,LENGTH,initial,inherit))
XMACRO(line_height,"line-height",normal,yes,yes,CSS1,(normal,NUMBER,LENGTH,PERCENT,initial,inherit))
XMACRO(list_style,"list-style",disc outside none,yes,no,CSS1)
XMACRO(list_style_image,"list-style-image",none,yes,no,CSS1,(none,URL,initial,inherit))
XMACRO(list_style_position,"list-style-position",outside,yes,no,CSS1,(inside,outside,initial,inherit))
XMACRO(list_style_type,"list-style-type",disc,yes,no,CSS1,(disc,armenian,circle,cjk-ideographic,decimal,decimal-leading-zero,georgian,hebrew,hiragana,hiragana-iroha,katakana,katakana-iroha,lower-alpha,lower-greek,lower-latin,lower-roman,none,square,upper-alpha,upper-greek,upper-latin,upper-roman,initial,inherit))
XMACRO(margin,"margin",0,no,yes,CSS1,(LENGTH,PERCENT,auto,initial,inherit))
XMACRO(margin_bottom,"margin-bottom",0,no,yes,CSS1,(LENGTH,PERCENT,auto,initial,inherit))
XMACRO(margin_left,"margin-left",0,no,yes,CSS1,(LENGTH,PERCENT,auto,initial,inherit))
XMACRO(margin_right,"margin-right",0,no,yes,CSS1,(LENGTH,PERCENT,auto,initial,inherit))
XMACRO(margin_top0,"margin-top0",no,yes,CSS1,(LENGTH,PERCENT,auto,initial,inherit))
XMACRO(max_height,"max-height",none,no,yes,CSS2,(none,LENGTH,PERCENT,initial,inherit))
XMACRO(max_width,"max-width",none,no,yes,CSS2,(none,LENGTH,PERCENT,initial,inherit))
XMACRO(min_height,"min-height",0,no,yes,CSS2,(LENGTH,PERCENT,initial,inherit))
XMACRO(min_width0,"min-width0",no,yes,CSS2,(LENGTH,PERCENT,initial,inherit))
XMACRO(mix_blend_mode,"mix-blend-mode",normal,no,no,CSS3,(normal,multiply,screen,overlay,darken,lighten,color-dodge,color-burn,difference,exclusion,hue,saturation,color,luminosity))
XMACRO(object_fit,"object-fit",initial,no,no,CSS3,(fill,contain,cover,none,scale-down,initial,inherit))
XMACRO(object_position,"object-position",50% 50%,yes,yes,CSS3)
XMACRO(opacity,"opacity",1,no,yes,CSS3,(NUMBER,initial,inherit))
XMACRO(order,"order",0,no,yes,CSS3,(NUMBER,initial,inherit))
XMACRO(outline,"outline",medium invert COLOR,no,yes,CSS2)
XMACRO(outline_color,"outline-color",invert,no,yes,CSS2,(invert,COLOR,initial,inherit))
XMACRO(outline_offset,"outline-offset",0,no,yes,CSS3,(LENGTH,initial,inherit))
XMACRO(outline_style,"outline-style",none,no,no,CSS2,(none,hidden,dotted,dashed,solid,double,groove,ridge,inset,outset,initial,inherit))
XMACRO(outline_width,"outline-width",medium,no,yes,CSS2,(medium,thin,thick,LENGTH,initial,inherit))
XMACRO(overflow,"overflow",visible,no,no,CSS2,(visible,hidden,scroll,auto,initial,inherit))
XMACRO(overflow_x,"overflow-x",visible,no,no,CSS3,(visible,hidden,scroll,auto,initial))
XMACRO(overflow_y,"overflow-y",visible,no,no,CSS3,(visible,hidden,scroll,auto,initial))
XMACRO(padding,"padding",0,no,yes,CSS1,(LENGTH,PERCENT,initial,inherit))
XMACRO(padding_bottom,"padding-bottom",0,no,yes,CSS1,(LENGTH,PERCENT,initial,inherit))
XMACRO(padding_left,"padding-left",0,no,yes,CSS1,(LENGTH,PERCENT,initial,inherit))
XMACRO(padding_right,"padding-right",0,no,yes,CSS1,(LENGTH,PERCENT,initial,inherit))
XMACRO(padding_top,"padding-top",0,no,yes,CSS1,(LENGTH,PERCENT,initial,inherit))
XMACRO(page_break_after,"page-break-after",auto,no,no,CSS2,(auto,always,avoid,left,right,initial,inherit))
XMACRO(page_break_before,"page-break-before",auto,no,no,CSS2,(auto,always,avoid,left,right,initial,inherit))
XMACRO(page_break_inside,"page-break-inside",auto,no,no,CSS2,(auto,avoid,initial,inherit))
XMACRO(perspective,"perspective",none,no,yes,CSS3,(LENGTH,none,initial,inherit))
XMACRO(perspective_origin,"perspective-origin",50% 50%,no,yes,CSS3)
XMACRO(pointer_events,"pointer-events",auto,yes,no,CSS3,(auto,none,initial,inherit))
XMACRO(position,"position",static,no,no,CSS2,(static,absolute,fixed,relative,sticky,initial,inherit))
XMACRO(quotes,"quotes",initial,yes,no,CSS2,(none,initial,inherit/*fixme*/))
XMACRO(resize,"resize",none,no,no,CSS3,(none,both,horizontal,vertical,initial,inherit))
XMACRO(right,"right",auto,no,yes,CSS2,(auto,LENGTH,PERCENT,initial,inherit))
XMACRO(scroll_behavior,"scroll-behavior",auto,no,no,CSSOM,(auto,smooth,initial,inherit))
XMACRO(tab_size,"tab-size",8,yes,no,CSS3,(NUMBER,LENGTH,initial,inherit))
XMACRO(table_layout,"table-layout",auto,no,no,CSS2,(auto,fixed,initial,inherit))
XMACRO(text_align,"text-align",initial,yes,no,CSS1,(left,right,center,justify,initial,inherit))
XMACRO(text_align_last,"text-align-last",auto,yes,no,CSS3,(auto,left,right,center,justify,start,end,intial,inherit))
XMACRO(text_decoration,"text-decoration",none currentcolor solid,no,no,CSS1)
XMACRO(text_decoration_color,"text-decoration-color",initial,no,yes,CSS3,(COLOR,initial,inherit))
XMACRO(text_decoration_line,"text-decoration-line",none,no,no,CSS3,(none,underline,overline,line-through,initial,inherit))
XMACRO(text_decoration_style,"text-decoration-style",solid,no,no,CSS3,(solid,double,dotted,dashed,wavy,initial,inherit))
XMACRO(text_indent,"text-indent",0,yes,yes,CSS1,(LENGTH,PERCENT,initial,inherit))
XMACRO(text_justify,"text-justify",auto,yes,no,CSS3,(auto,inter-word,inter-character,none,initial,inherit))
XMACRO(text_overflow,"text-overflow",clip,no,no,CSS3,(clip,ellipsis,string,initial,inherit))
XMACRO(text_shadow,"text-shadow",none,yes,yes,CSS3)
XMACRO(text_transform,"text-transform",none,yes,no,CSS1,(none,capitalize,uppercase,lowercase,initial,inherit))
XMACRO(top,"top",auto,no,yes,CSS2,(auto,LENGTH,PERCENT,initial,inherit))
XMACRO(transform,"transform",none,no,yes,CSS3)
XMACRO(transform_origin,"transform-origin",50% 50% 0,no,yes,CSS3)
XMACRO(transform_style,"transform-style",flat,no,no,CSS3,(flat,preserve-3d,initial,inherit))
XMACRO(transition,"transition",all 0s ease 0s,no,no,CSS3)
XMACRO(transition_delay,"transition-delay",0s,no,no,CSS3,(TIME,initial,inherit))
XMACRO(transition_duration,"transition-duration",0s,no,no,CSS3,(TIME,initial,inherit))
XMACRO(transition_property,"transition-property",all,no,no,CSS3,(none,all,/*fixme*/initial,inherit))
XMACRO(transition_timing_function,"transition-timing-function",ease,no,no,CSS3,(ease,linear,ease-in,ease-out,ease-in-out,step-start,step-end,STEPS,CUBIC_BEZIER,initial,inherit))
XMACRO(unicode_bidi,"unicode-bidi",normal,yes,no,CSS2,(normal,embed,bidi-override,isolate,isolate-override,plaintext,initial,inherit))
XMACRO(user_select,"user-select",auto,no,no,CSS3,(auto,none,text,all))
XMACRO(vertical_align,"vertical-align",baseline,no,yes,CSS1,(baseline,LENGTH,PERCENT,sub,super,top,text-top,middle,bottom,text-bottom,initial,inherit))
XMACRO(visibility,"visibility",visible,yes,yes,CSS2,(visible,hidden,collapse,initial,inherit))
XMACRO(white_space,"white-space",normal,yes,no,CSS1,(normal,nowrap,pre,pre-line,pre-wrap,initial,inherit))
XMACRO(width,"width",auto,no,yes,CSS1,(auto,LENGTH,PERCENT,initial,inherit))
XMACRO(word_break,"word-break",normal,yes,no,CSS3,(normal,break-all,keep-all,break-word,initial,inherit))
XMACRO(word_spacing,"word-spacing",normal,yes,yes,CSS1,(normal,LENGTH,initial,inherit))
XMACRO(word_wrap,"word-wrap",normal,yes,no,CSS3,(normal,break-word,initial,inherit))
XMACRO(writing_mode,"writing-mode",horizontal-tb,yes,no,CSS3,(horizontal-tb,vertical-rl,vertical-lr))
XMACRO(z_index,"z-index",auto,no,yes,CSS2,(auto,NUMBER,initial,inherit))
